# Put application-specific config here (application name: client-config-app)
some:
    property: coffee
    other:
        property: is really good
cnumber:
  list:
    - name: C1
      url: 1.1.1.1
    - name: C2
      url: 2.2.2.2
    - name: C3
      url: 3.3.3.3